Style/FrozenStringLiteralComment:
  Enabled: false
Layout/LineLength:
  Max: 110
Metrics/BlockLength:
  Max: 100
Metrics/MethodLength:
  Max: 20
Style/StringLiterals:
  Enabled: false
Style/WordArray:
  Enabled: false
