version: 2.1
orbs: # Reusable configuration objects from CircleCI
  ruby: circleci/ruby@1.1.3
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.5-node
    working_directory: ~/zenflow-build
    steps:
      - run: git clone https://github.com/zencoder/zenflow ~/zenflow-build
      - run: gem install bundler --version 2.1.4
      - ruby/install-deps # Using the orb to install deps
      - run: echo "Ruby build"
      - ruby/rspec-test
workflows:
  build_and_test:
    jobs:
      - build
